### ISSUE TITLE
Getting Error while Creating Nodes

### ISSUE THREAD

**Issue by fauh45** [themetalfleece/neogma#31]
While running this code,
```typescript
import "dotenv/config";

import { neogma } from "../helpers/graph";
import { Interest } from "../helpers/graph/Interest";
import { Post } from "../helpers/graph/Post";
import { User } from "../helpers/graph/User";

const testNeo4J = async () => {
  const user_1 = await User.createOne({
    id: "1",
    username: "1",
  });

  const user_2 = await User.createOne({
    id: "2",
    username: "2",
  });

  const interest = await Interest.createOne({
    id: "int",
    name: "int",
  });

  const post = await Post.createOne({
    id: "1",
    deleted: false,
  });

  await post.relateTo({
    alias: "PartOfInterest",
    where: {
      id: "int",
    },
  });

  await post.relateTo({
    alias: "PostedByUser",
    where: {
      id: "1",
    },
  });

  await user_1.relateTo({
    alias: "LikesInterest",
    where: {
      id: "int",
    },
  });

  await user_2.relateTo({
    alias: "InteractWithPost",
    where: {
      id: "1",
    },
  });

  console.log(user_1);
  console.log(user_2);
  console.log(interest);
  console.log(post);

  await user_1.delete();
  await user_2.delete();
  await interest.delete();
  await post.delete();

  await neogma.driver.close();
};

testNeo4J()
  .then(() => console.log("Done"))
  .catch((err) => console.error(err))
  .finally(() => process.exit());
```

I found myself with this error,
```
TypeError: _a.call is not a function
    at QueryRunner.log (D:\Code\<redacted>\node_modules\neogma\dist\Queries\QueryRunner\QueryRunner.js:160:68)
    at D:\Code\<redacted>\node_modules\neogma\dist\Queries\QueryRunner\QueryRunner.js:183:18
    at Object.getRunnable (D:\Code\<redacted>\node_modules\neogma\dist\Sessions\Sessions.js:50:16)
    at QueryRunner.run (D:\Code\<redacted>\node_modules\neogma\dist\Queries\QueryRunner\QueryRunner.js:170:27)
    at D:\Code\<redacted>\node_modules\neogma\dist\Queries\QueryBuilder\QueryBuilder.js:414:32
    at Object.getSession (D:\Code\<redacted>\node_modules\neogma\dist\Sessions\Sessions.js:14:30)
    at Object.getRunnable (D:\Code\<redacted>\node_modules\neogma\dist\Sessions\Sessions.js:52:20)
    at QueryBuilder.run (D:\Code\<redacted>\node_modules\neogma\dist\Queries\QueryBuilder\QueryBuilder.js:413:27)
    at Function.createMany (D:\Code\<redacted>\node_modules\neogma\dist\ModelOps\ModelOps.js:420:22)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Done in 13.28s.
```

I've tried using Neo4J Desktop, Neo4J Sandbox, and Neo4J Aura and nothing does works, it produces the same error.

**Comment by fauh45** [comment]
Just found the problem, the `logger` options cannot be used with `pino-logger`. Sorry for this!

**Comment by themetalfleece** [comment]
Hey there! I'm glad you figured this out.
But I'd like to get to the bottom of this. Could you send me the relevant code that makes it error out when you're using pino? I've never heard of it so far, and I've tried the following, which doesn't throw any errors:
```ts
import * as pino from 'pino';
const logger = pino();

export const neogma = new Neogma(
    {
        url: process.env.NEO4J_URL || '',
        username: process.env.NEO4J_USERNAME || '',
        password: process.env.NEO4J_PASSWORD || '',
    },
    {
        encrypted: false,
        logger: (v: string) => logger.info(v),
    },
);
```

However, the format of the logs is not right, which is brought to my attention now. It's an easy fix though, but I'll wait to see if I'm missing something with Pino which can be implemented.

**Comment by fauh45** [comment]
What I was trying is actually, something like this,

```typescript
import * as pino from 'pino';
const logger = pino();

export const neogma = new Neogma(
    {
        url: process.env.NEO4J_URL || '',
        username: process.env.NEO4J_USERNAME || '',
        password: process.env.NEO4J_PASSWORD || '',
    },
    {
        encrypted: false,
        logger: logger,
    },
);
```

Which makes the error, because it tries to call `logger(val)` and your code snippets would work just fine. I think what could be great is to actually have different level of logs, like with errors neogma actually call for `logger.error(val)`, so that in production it can be controlled more easily, as the logger is a single instance, so do the log level of it.

Also a little out of topic here, but I think the docs should explain about how to handle cyclical dependencies more, or at least gave some example. Just a suggestion.

**Comment by themetalfleece** [comment]
I see, I hadn't considered this level of logging but it should come in handy for sure.

I agree with the documentation issue, I've had more people look for it. It's actually mentioned in the documentation but hard to find, so a separate section for it would be much better.

**Comment by themetalfleece** [comment]
Added various parts to the documentation for clarity, including:
- https://themetalfleece.github.io/neogma-docs/docs/Models/Defining-a-Model#importing-neogma
- https://themetalfleece.github.io/neogma-docs/docs/Models/Defining-a-Model#relating-a-model-to-itself
- https://themetalfleece.github.io/neogma-docs/docs/Models/Defining-a-Model#declaring-bidirectional-relationships
